### ISSUE TITLE
yarn server:add not working

### ISSUE THREAD

**Issue by jukefr** [jukefr/Lardons#2]
might be node version problem

**Comment by jukefr** [comment]
very weird issue :
if i run from inside the container in `/home/default/server` the following : `node_modules/strapi/bin/strapi.js "install" "graphql"` it works with no problem

if I run it from outside the container with `docker exec --user default node npm --prefix server run strapi install graphql` I get the following:
```
$ docker-compose exec --user default node npm --prefix server run strapi install $PLUGIN

> server@0.1.0 strapi /home/default/server
> node_modules/strapi/bin/strapi.js "install" "graphql"

[2018-07-23T12:52:00.880Z] debug Installation in progress...
[2018-07-23T12:52:00.882Z] debug Installing the plugin from npm registry.
[2018-07-23T12:52:01.281Z] error An error occurred during plugin installation. 
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-graphql
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.1.0 strapi: `node_modules/strapi/bin/strapi.js "install" "graphql"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@0.1.0 strapi script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/default/.npm/_logs/2018-07-23T12_52_01_288Z-debug.log
error Command failed with exit code 1.
```
detailed log :
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   'server',
1 verbose cli   'run',
1 verbose cli   'strapi',
1 verbose cli   'install',
1 verbose cli   'graphql' ]
2 info using npm@6.2.0
3 info using node@v9.11.1
4 verbose run-script [ 'prestrapi', 'strapi', 'poststrapi' ]
5 info lifecycle server@0.1.0~prestrapi: server@0.1.0
6 info lifecycle server@0.1.0~strapi: server@0.1.0
7 verbose lifecycle server@0.1.0~strapi: unsafe-perm in lifecycle true
8 verbose lifecycle server@0.1.0~strapi: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/default/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle server@0.1.0~strapi: CWD: /home/default/server
10 silly lifecycle server@0.1.0~strapi: Args: [ '-c',
10 silly lifecycle   'node_modules/strapi/bin/strapi.js "install" "graphql"' ]
11 silly lifecycle server@0.1.0~strapi: Returned: code: 1  signal: null
12 info lifecycle server@0.1.0~strapi: Failed to exec strapi script
13 verbose stack Error: server@0.1.0 strapi: `node_modules/strapi/bin/strapi.js "install" "graphql"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid server@0.1.0
15 verbose cwd /home/default
16 verbose Linux 4.17.9-041709-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "server" "run" "strapi" "install" "graphql"
18 verbose node v9.11.1
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error server@0.1.0 strapi: `node_modules/strapi/bin/strapi.js "install" "graphql"`
22 error Exit status 1
23 error Failed at the server@0.1.0 strapi script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
